/* ═══ ANALYTICS — Stats, categories, streak ring, pace chart, Year in Review ═══ */
// ══════ ANALYTICS ══════
function renderAnalytics(){
const comp=getCompleted(),goal=getGoal(),pct=Math.min(100,Math.round(comp.length/goal*100)),totalPages=comp.reduce((s,b)=>s+(b.pages||0),0);
const avgDays=(()=>{const ds=comp.filter(b=>b.startDate&&b.endDate).map(b=>daysBetween(b.startDate,b.endDate));return ds.length?Math.round(ds.reduce((a,c)=>a+c,0)/ds.length):0})();
const streak=getStreak(),allQuotes=[];data.books.forEach(b=>(b.quotes||[]).forEach(q=>allQuotes.push(q)));const annotated=data.books.filter(b=>b.notes||b.coreArgument||b.impact||(b.quotes&&b.quotes.length>0)).length;
let html=`<div class="mini-stats"><div class="mini-stat"><p class="mini-stat-label">Completed</p><p class="mini-stat-value">${comp.length}</p><p class="mini-stat-sub">of ${goal}</p></div><div class="mini-stat"><p class="mini-stat-label">Avg Pace</p><p class="mini-stat-value">${avgDays?avgDays+"d":"\u2014"}</p><p class="mini-stat-sub">per book</p></div><div class="mini-stat"><p class="mini-stat-label">Pages</p><p class="mini-stat-value">${totalPages.toLocaleString()}</p></div><div class="mini-stat"><p class="mini-stat-label">Streak</p><p class="mini-stat-value">${streak.weeks?streak.weeks+"w":"\u2014"}</p></div><div class="mini-stat"><p class="mini-stat-label">Annotated</p><p class="mini-stat-value">${annotated}</p></div><div class="mini-stat"><p class="mini-stat-label">Quotes</p><p class="mini-stat-value">${allQuotes.length}</p></div></div>`;
html+=`<div class="panel"><div class="panel-title">Annual Progress</div><div class="progress-row"><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div><span class="progress-pct">${pct}%</span></div></div>`;
// Streak Ring
const sessionDays={};data.books.forEach(b=>(b.sessions||[]).forEach(s=>{if(!s.date)return;const k=s.date.slice(0,10);sessionDays[k]=(sessionDays[k]||0)+1}));
const atToday=new Date();atToday.setHours(0,0,0,0);let aStreak=0;for(let d=new Date(atToday);;d.setDate(d.getDate()-1)){if(sessionDays[d.toISOString().slice(0,10)])aStreak++;else break}
let aBestStreak=0,aCS=0;const aDayKeys=Object.keys(sessionDays).sort();aDayKeys.forEach((k,i)=>{if(i===0)aCS=1;else{const p=new Date(aDayKeys[i-1]);p.setDate(p.getDate()+1);aCS=p.toISOString().slice(0,10)===k?aCS+1:1}if(aCS>aBestStreak)aBestStreak=aCS});
const aTodayKey=atToday.toISOString().slice(0,10),aDow=atToday.getDay()===0?6:atToday.getDay()-1;
const aWeekStart=new Date(atToday);aWeekStart.setDate(aWeekStart.getDate()-aDow);let aWeekRead=0;
for(let i=0;i<7;i++){const wd=new Date(aWeekStart);wd.setDate(wd.getDate()+i);if(sessionDays[wd.toISOString().slice(0,10)])aWeekRead++}
const aCm=atToday.getMonth(),aCy=atToday.getFullYear(),aDim=new Date(aCy,aCm+1,0).getDate();let aMonthRead=0;
for(let d=1;d<=aDim;d++){const dk=`${aCy}-${String(aCm+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;if(sessionDays[dk])aMonthRead++}
const aRMax=Math.max(aBestStreak,7),aRPct=Math.min(100,Math.round(aStreak/aRMax*100)),aRR=50,aRC=2*Math.PI*aRR,aRO=aRC-(aRPct/100)*aRC;
html+=`<div class="panel"><div class="panel-title">Reading Streak</div><div class="sr-row"><div class="sr-ring-wrap"><svg viewBox="0 0 120 120" width="100" height="100"><circle cx="60" cy="60" r="${aRR}" fill="none" stroke="var(--border)" stroke-width="8"/><circle cx="60" cy="60" r="${aRR}" fill="none" stroke="var(--accent)" stroke-width="8" stroke-dasharray="${aRC}" stroke-dashoffset="${aRO}" stroke-linecap="round" transform="rotate(-90 60 60)"/></svg><div class="sr-ring-inner"><span class="sr-ring-num">${aStreak}</span><span class="sr-ring-label">day${aStreak!==1?'s':''}</span></div></div><div class="sr-details"><div class="sr-detail"><span class="sr-detail-label">Current streak</span><span class="sr-detail-val accent">${aStreak} day${aStreak!==1?'s':''}</span></div><div class="sr-detail"><span class="sr-detail-label">Best streak</span><span class="sr-detail-val">${aBestStreak} day${aBestStreak!==1?'s':''}</span></div><div class="sr-detail"><span class="sr-detail-label">This month</span><span class="sr-detail-val">${aMonthRead} / ${aDim} days</span></div><div class="sr-detail"><span class="sr-detail-label">This week</span><span class="sr-detail-val accent">${aWeekRead} / 7 days</span></div></div></div>`;
const aDayLabels=['M','T','W','T','F','S','S'];let aTwC='',aTwL='';for(let i=0;i<7;i++){const wd=new Date(aWeekStart);wd.setDate(wd.getDate()+i);const wk=wd.toISOString().slice(0,10);aTwC+=`<div class="sr-tw-day${sessionDays[wk]?' read':''}${wk===aTodayKey?' today':''}"></div>`;aTwL+=`<span class="sr-tw-label">${aDayLabels[i]}</span>`}
html+=`<div class="sr-this-week">${aTwC}</div><div class="sr-tw-labels">${aTwL}</div></div>`;
// Category Breakdown
const catData=CATEGORIES.map(c=>({name:c,value:comp.filter(b=>b.category===c).length})).filter(c=>c.value>0);
if(catData.length)html+=`<div class="panel"><div class="panel-title">Category Breakdown</div><div class="pie-row"><div class="pie-wrap"><canvas id="pieChart"></canvas></div><div class="cat-legend">${catData.sort((a,b)=>b.value-a.value).map(c=>`<div class="cat-legend-item"><div class="cat-legend-dot" style="background:${CAT_COLORS[c.name]}"></div><span class="cat-legend-name">${c.name}</span><span class="cat-legend-count">${c.value}</span><div class="cat-legend-bar"><div class="cat-legend-bar-fill" style="width:${(c.value/comp.length)*100}%;background:${CAT_COLORS[c.name]}"></div></div></div>`).join("")}</div></div></div>`;
// Pace chart
const mm={};comp.forEach(b=>{if(b.endDate){const d=new Date(b.endDate),k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;mm[k]=(mm[k]||0)+1}});const sm=Object.keys(mm).sort();
if(sm.length)html+=`<div class="panel"><div class="panel-title">Reading Pace</div><canvas class="pace-chart" id="paceChart"></canvas></div>`;
// Goals & Challenges
const catGoals=data.settings.goals.categories||{},challenges=data.settings.goals.challenges||[];
if(Object.keys(catGoals).length||challenges.length){html+=`<div class="panel"><div class="panel-title">Goals &amp; Challenges</div>`;
if(Object.keys(catGoals).length){html+=`<div class="goal-panel-section"><p class="goal-panel-section-title">Category Goals</p>`;Object.entries(catGoals).forEach(([cat,target])=>{const prog=getCategoryProgress(cat);if(!prog)return;const color=CAT_COLORS[cat]||CAT_COLORS.Other;html+=`<div style="margin-bottom:10px"><div style="display:flex;justify-content:space-between;font-family:var(--ui);font-size:12px;margin-bottom:3px"><span style="color:var(--textM)">${cat}</span><span style="color:var(--textD)">${prog.count}/${prog.target}</span></div><div class="challenge-progress-bar"><div class="challenge-progress-fill" style="width:${prog.pct}%;background:${color}"></div></div></div>`});html+=`</div>`}
if(challenges.length){html+=`<div class="goal-panel-section"><p class="goal-panel-section-title">Challenges</p>`;challenges.forEach(ch=>{const prog=getChallengeProgress(ch);html+=`<div class="challenge-card${prog.done?" challenge-done":""}"><p class="challenge-label">${esc(ch.label)}</p><p class="challenge-meta">${ch.type} \u00B7 ${prog.current}/${ch.target}</p><div class="challenge-progress-bar"><div class="challenge-progress-fill" style="width:${prog.pct}%"></div></div><p class="challenge-pct">${prog.pct}%</p></div>`});html+=`</div>`}
html+=`</div>`}
// Reading Habits
const allSessions=[];data.books.forEach(b=>(b.sessions||[]).forEach(s=>allSessions.push(s)));
if(allSessions.length){const totalMins=allSessions.reduce((s,x)=>s+x.duration,0),avgMins=Math.round(totalMins/allSessions.length);
const totalSessionPages=allSessions.reduce((s,x)=>s+((x.endPage||0)-(x.startPage||0)),0);const pagesPerHour=totalMins>0?Math.round(totalSessionPages/(totalMins/60)):0;
const dayNames=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],dayCounts=[0,0,0,0,0,0,0];allSessions.forEach(s=>{if(s.date){const d=new Date(s.date).getDay();dayCounts[d]++}});const maxDay=Math.max(...dayCounts)||1;
const now=Date.now(),weekMs=7*86400000;const thisWeek=allSessions.filter(s=>{const t=new Date(s.date).getTime();return t>=now-weekMs}).length;const lastWeek=allSessions.filter(s=>{const t=new Date(s.date).getTime();return t>=now-2*weekMs&&t<now-weekMs}).length;
html+=`<div class="panel"><div class="panel-title">Reading Habits</div><div class="mini-stats" style="margin-bottom:16px"><div class="mini-stat"><p class="mini-stat-label">Total Time</p><p class="mini-stat-value">${totalMins>=60?Math.round(totalMins/60)+"h":totalMins+"m"}</p></div><div class="mini-stat"><p class="mini-stat-label">Avg Session</p><p class="mini-stat-value">${avgMins}m</p></div>${pagesPerHour?`<div class="mini-stat"><p class="mini-stat-label">Pages/Hour</p><p class="mini-stat-value">${pagesPerHour}</p></div>`:""}<div class="mini-stat"><p class="mini-stat-label">This Week</p><p class="mini-stat-value">${thisWeek}</p><p class="mini-stat-sub">vs ${lastWeek} last week</p></div></div><p style="font-family:var(--ui);font-size:11px;color:var(--textD);text-transform:uppercase;letter-spacing:0.08em;font-weight:500;margin-bottom:8px">Reading Days</p><div class="reading-habits">${dayNames.map((d,i)=>`<div class="habit-row"><span class="habit-label">${d}</span><div class="habit-bar"><div class="habit-fill" style="width:${(dayCounts[i]/maxDay)*100}%"></div></div><span class="habit-val">${dayCounts[i]}</span></div>`).join("")}</div></div>`}
// Theme Index
const allThemes={};data.books.forEach(b=>(b.themes||[]).forEach(t=>{if(!allThemes[t])allThemes[t]={name:t,books:[]};allThemes[t].books.push(b)}));const themeEntries=Object.values(allThemes).sort((a,b)=>b.books.length-a.books.length);
if(themeEntries.length){html+=`<div class="panel"><div class="panel-title">Themes</div><div class="theme-index" id="themeIdx">${themeEntries.map(t=>`<div class="theme-index-item"><div class="theme-index-header" data-theme="${esc(t.name)}"><span class="theme-index-name">${esc(t.name)}</span><span class="theme-index-count">${t.books.length}</span><span class="theme-index-chevron">&#9656;</span></div><div class="theme-index-books"><div class="theme-index-books-inner">${t.books.map(b=>{const lc=CAT_COLORS[b.category]||CAT_COLORS.Other;return`<div class="theme-book-mini" data-id="${b.id}"><p class="theme-book-mini-title">${esc(b.title)}</p><p class="theme-book-mini-author">${esc(b.author)}</p></div>`}).join("")}</div></div></div>`).join("")}</div></div>`}
document.getElementById("viewAnalytics").innerHTML=html;
requestAnimationFrame(()=>{if(catData.length)drawPie(catData,comp.length);if(sm.length)drawPace(mm,sm);
const idx=document.getElementById("themeIdx");if(idx){idx.querySelectorAll(".theme-index-header").forEach(h=>h.onclick=()=>h.closest(".theme-index-item").classList.toggle("expanded"));idx.querySelectorAll(".theme-book-mini").forEach(b=>b.onclick=()=>openDetail(b.dataset.id))}});
}

function drawPie(cd,total){const c=document.getElementById("pieChart");if(!c)return;const dpr=window.devicePixelRatio||1;c.width=170*dpr;c.height=170*dpr;const ctx=c.getContext("2d");ctx.scale(dpr,dpr);let start=-Math.PI/2;cd.forEach(d=>{const sw=(d.value/total)*Math.PI*2;ctx.beginPath();ctx.arc(85,85,75,start,start+sw);ctx.arc(85,85,42,start+sw,start,true);ctx.closePath();ctx.fillStyle=CAT_COLORS[d.name]||"#7A7670";ctx.fill();start+=sw})}
function drawPace(mm,sm){const c=document.getElementById("paceChart");if(!c)return;const dpr=window.devicePixelRatio||1;const rect=c.getBoundingClientRect();c.width=rect.width*dpr;c.height=rect.height*dpr;const ctx=c.getContext("2d");ctx.scale(dpr,dpr);const w=rect.width,h=rect.height;let cum=0;const pts=sm.map(k=>{cum+=mm[k];const[y,m]=k.split("-");return{label:new Date(parseInt(y),parseInt(m)-1).toLocaleDateString("en-US",{month:"short",year:"2-digit"}),books:mm[k],cum}});const maxC=Math.max(...pts.map(p=>p.cum),1);const pL=36,pR=20,pT=20,pB=30,cw=w-pL-pR,ch=h-pT-pB;ctx.strokeStyle="#2A2419";ctx.lineWidth=1;for(let i=0;i<=4;i++){const y=pT+(ch/4)*i;ctx.beginPath();ctx.moveTo(pL,y);ctx.lineTo(w-pR,y);ctx.stroke()}const grad=ctx.createLinearGradient(0,pT,0,h-pB);grad.addColorStop(0,"rgba(196,149,106,0.25)");grad.addColorStop(1,"rgba(196,149,106,0)");ctx.beginPath();pts.forEach((p,i)=>{const x=pL+(i/(pts.length-1||1))*cw,y=pT+ch-(p.cum/maxC)*ch;i===0?ctx.moveTo(x,y):ctx.lineTo(x,y)});ctx.lineTo(pL+cw,pT+ch);ctx.lineTo(pL,pT+ch);ctx.closePath();ctx.fillStyle=grad;ctx.fill();ctx.beginPath();pts.forEach((p,i)=>{const x=pL+(i/(pts.length-1||1))*cw,y=pT+ch-(p.cum/maxC)*ch;i===0?ctx.moveTo(x,y):ctx.lineTo(x,y)});ctx.strokeStyle="#C4956A";ctx.lineWidth=2;ctx.stroke();pts.forEach((p,i)=>{const x=pL+(i/(pts.length-1||1))*cw,y=pT+ch-(p.cum/maxC)*ch;ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fillStyle="#C4956A";ctx.fill()});ctx.font="11px Outfit,sans-serif";ctx.fillStyle="#6A6258";ctx.textAlign="center";pts.forEach((p,i)=>{ctx.fillText(p.label,pL+(i/(pts.length-1||1))*cw,h-6)});ctx.textAlign="right";for(let i=0;i<=4;i++)ctx.fillText(Math.round((maxC/4)*(4-i)),pL-8,pT+(ch/4)*i+4)}

// ══════ YEAR IN REVIEW ══════
function renderReview(){const comp=getCompleted();if(comp.length<3){document.getElementById("viewReview").innerHTML=`<div class="empty"><p class="title">Complete at least 3 books to unlock Year in Review.</p></div>`;return}
const totalPages=comp.reduce((s,b)=>s+(b.pages||0),0),pct=Math.min(100,Math.round(comp.length/getGoal()*100));const catCounts={};comp.forEach(b=>{catCounts[b.category]=(catCounts[b.category]||0)+1});const topCat=Object.entries(catCounts).sort((a,b)=>b[1]-a[1])[0];const rated=comp.filter(b=>b.rating);const avgR=rated.length?(rated.reduce((s,b)=>s+b.rating,0)/rated.length).toFixed(1):null;
const durs=comp.filter(b=>b.startDate&&b.endDate).map(b=>({...b,days:daysBetween(b.startDate,b.endDate)}));const fastest=durs.length?durs.reduce((a,b)=>a.days<b.days?a:b):null;const longest=comp.reduce((a,b)=>(b.pages||0)>(a.pages||0)?b:a,comp[0]);const topRated=[...comp].filter(b=>b.rating).sort((a,b)=>b.rating-a.rating)[0];
const allThemes={};data.books.forEach(b=>(b.themes||[]).forEach(t=>{allThemes[t]=(allThemes[t]||0)+1}));const topThemes=Object.entries(allThemes).sort((a,b)=>b[1]-a[1]).slice(0,5);
const totalQuotes=data.books.reduce((s,b)=>s+(b.quotes?.length||0),0);const ms=getMilestones();
let html=`<div class="yr-hero"><div class="yr-hero-glow"></div><p class="yr-hero-label">Year in Review</p><p class="yr-hero-num">${comp.length}</p><p class="yr-hero-sub">books completed \u00B7 ${pct}% of goal</p>${totalPages?`<p class="yr-hero-pages">${totalPages.toLocaleString()} pages read</p>`:""}</div><div class="yr-grid">`;
if(topCat)html+=`<div class="yr-card"><p class="yr-card-label">Top Category</p><p class="yr-card-value">${topCat[0]}</p><p class="yr-card-sub">${topCat[1]} books</p></div>`;if(avgR)html+=`<div class="yr-card"><p class="yr-card-label">Avg Rating</p><p class="yr-card-value">${avgR} / 5</p></div>`;if(fastest)html+=`<div class="yr-card"><p class="yr-card-label">Fastest Read</p><p class="yr-card-value sm">${esc(fastest.title)}</p><p class="yr-card-sub">${fastest.days} days</p></div>`;if(longest&&longest.pages)html+=`<div class="yr-card"><p class="yr-card-label">Longest Book</p><p class="yr-card-value sm">${esc(longest.title)}</p><p class="yr-card-sub">${longest.pages} pages</p></div>`;if(topRated)html+=`<div class="yr-card"><p class="yr-card-label">Highest Rated</p><p class="yr-card-value sm">${esc(topRated.title)}</p><p class="yr-card-sub">${topRated.rating}/5</p></div>`;html+=`</div>`;
if(topThemes.length)html+=`<div class="panel"><div class="panel-title">Recurring Themes</div><div class="yr-themes">${topThemes.map(([t,c])=>`<div class="yr-theme">${esc(t)} <em>\u00D7${c}</em></div>`).join("")}</div></div>`;
if(ms.length)html+=`<div class="panel"><div class="panel-title">Milestones</div><div class="yr-milestones">${ms.map(m=>`<div class="yr-milestone"><span class="yr-milestone-icon">${m.icon}</span><p class="yr-milestone-label">${m.label}</p></div>`).join("")}</div></div>`;
if(totalQuotes)html+=`<div style="background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:18px 24px;display:flex;align-items:center;gap:14px"><span style="color:var(--accentDim);font-size:20px">\u201C</span><p style="font-family:var(--ui);font-size:13px;color:var(--textM);margin:0">You saved <strong style="color:var(--text)">${totalQuotes}</strong> passage${totalQuotes!==1?"s":""} across your readings.</p></div>`;
document.getElementById("viewReview").innerHTML=html;
}
