/* ═══ APP — Search API, add/edit form, settings, import/export, wiring ═══ */
// ══════ BOOK SEARCH API ══════
function mapCategory(apiCats){if(!apiCats||!apiCats.length)return"Other";const text=apiCats.join(" ").toLowerCase();const map=[["Self-Awareness",["self-help","psychology","mindfulness","habits","motivation","personal growth"]],["Current America",["american politics","current affairs","social justice","political science"]],["Economics & Money",["economics","finance","business","investing","money","entrepreneurship"]],["Technology",["technology","computer","programming","artificial intelligence","software","engineering"]],["American History",["american history","civil war","founding fathers","united states history"]],["Science",["science","physics","biology","mathematics","neuroscience","chemistry","astronomy"]],["World History",["world history","ancient","civilization","medieval","global history"]],["Philosophy & Ethics",["philosophy","ethics","stoic","existential","moral","logic"]],["Religion",["religion","theology","bible","christianity","buddhism","islam","spirituality"]],["Fiction",["fiction","novel","fantasy","sci-fi","mystery","thriller","literary","romance","horror"]]];for(const[cat,kw]of map)if(kw.some(k=>text.includes(k)))return cat;if(text.includes("history"))return"World History";return"Other"}
async function searchBooks(query){const q=encodeURIComponent(query.trim());const[gRes,olRes]=await Promise.allSettled([fetch(`https://www.googleapis.com/books/v1/volumes?q=${q}&maxResults=5`).then(r=>r.json()),fetch(`https://openlibrary.org/search.json?q=${q}&limit=5&fields=title,author_name,number_of_pages_median,subject`).then(r=>r.json())]);const results=[];if(gRes.status==="fulfilled"&&gRes.value.items){for(const item of gRes.value.items){const v=item.volumeInfo||{};results.push({title:v.title||"",author:(v.authors||[]).join(", "),pages:v.pageCount||null,category:mapCategory(v.categories||[]),source:"google"})}}if(olRes.status==="fulfilled"&&olRes.value.docs){for(const doc of olRes.value.docs){results.push({title:doc.title||"",author:(doc.author_name||[]).join(", "),pages:doc.number_of_pages_median||null,category:mapCategory(doc.subject||[]),source:"openlibrary"})}}if(!results.length&&gRes.status==="rejected"&&olRes.status==="rejected")throw new Error("Search failed.");const seen=new Set(),deduped=[];for(const r of results){const key=(r.title+"|"+r.author).toLowerCase().replace(/\s+/g," ");if(!seen.has(key)){seen.add(key);deduped.push(r)}}return deduped.slice(0,8)}

// ══════ ADD/EDIT FORM ══════
function openForm(book){const isEdit=!!book;
// Smart defaults for new books
const defaultStatus=!isEdit?(getReading().length===0?"reading":"want-to-read"):"";
const lastCat=!isEdit?(data.books.length?data.books[data.books.length-1].category:"Self-Awareness"):"";
const today=new Date().toISOString().slice(0,10);
const defStart=!isEdit&&defaultStatus==="reading"?today:(book?.startDate||"");
const defCat=book?.category||lastCat;
const defStat=book?.status||defaultStatus;
document.getElementById("formPanel").innerHTML=`<div class="modal-header"><h2>${isEdit?"Edit":"Add"} Book</h2><button class="modal-close" id="formClose">&times;</button></div><div class="form-stack">${!isEdit?`<div class="book-search-section"><p class="form-label">Search &amp; Auto-fill</p><div class="book-search-row"><input id="fSearchInput" placeholder="Search by title or author..."><button class="book-search-btn" id="fSearchBtn">Search</button></div><div id="fSearchResults"></div></div>`:""}<div><p class="form-label">Title *</p><input class="form-input" id="fTitle" placeholder="Book title" value="${esc(book?.title||"")}"></div><div><p class="form-label">Author</p><input class="form-input" id="fAuthor" placeholder="Author name" value="${esc(book?.author||"")}"></div><div class="form-row"><div><p class="form-label">Category</p><select class="form-input" id="fCategory">${CATEGORIES.map(c=>`<option value="${c}"${defCat===c?" selected":""}>${c}</option>`).join("")}</select></div><div><p class="form-label">Status</p><select class="form-input" id="fStatus"><option value="want-to-read"${defStat==="want-to-read"?" selected":""}>To Read</option><option value="reading"${defStat==="reading"?" selected":""}>Reading</option><option value="completed"${defStat==="completed"?" selected":""}>Completed</option><option value="abandoned"${defStat==="abandoned"?" selected":""}>Dropped</option></select></div></div><div class="form-row three"><div><p class="form-label">Pages</p><input class="form-input" type="number" id="fPages" value="${book?.pages||""}"></div><div><p class="form-label">Started</p><input class="form-input" type="date" id="fStart" value="${defStart}"></div><div><p class="form-label">Finished</p><input class="form-input" type="date" id="fEnd" value="${book?.endDate||""}"></div></div><div><p class="form-label">Notes</p><textarea class="form-input" id="fNotes">${esc(book?.notes||"")}</textarea></div></div><button class="form-submit" id="formSave">${isEdit?"Save":"Add to Library"}</button>`;
document.getElementById("formModal").classList.add("open");document.getElementById("formClose").onclick=()=>document.getElementById("formModal").classList.remove("open");
// Smart date auto-fill on status change
document.getElementById("fStatus").onchange=function(){const td=new Date().toISOString().slice(0,10);const s=document.getElementById("fStart"),e=document.getElementById("fEnd");if(this.value==="reading"&&!s.value)s.value=td;if(this.value==="completed"){if(!s.value)s.value=td;if(!e.value)e.value=td}};
// Book search
if(!isEdit){let lastSR=[];const si=document.getElementById("fSearchInput"),sb=document.getElementById("fSearchBtn"),sr=document.getElementById("fSearchResults");
const doSearch=async()=>{const q=si.value.trim();if(!q)return;sb.disabled=true;sr.innerHTML='<div class="book-search-loading">Searching\u2026</div>';try{lastSR=await searchBooks(q);if(!lastSR.length){sr.innerHTML='<p class="book-search-empty">No results.</p>';return}sr.innerHTML=lastSR.map((r,i)=>`<div class="book-search-item" data-idx="${i}"><span class="book-search-item-title">${esc(r.title)}</span><span class="book-search-item-author">${esc(r.author||"Unknown")}</span><div class="book-search-item-meta">${r.pages?`<span>${r.pages}p</span>`:""}<span>${esc(r.category)}</span><span class="book-search-source ${r.source}">${r.source==="google"?"Google":"OpenLib"}</span></div></div>`).join("")}catch(e){sr.innerHTML=`<p class="book-search-error">${esc(e.message)}</p>`}finally{sb.disabled=false}};
sb.onclick=doSearch;si.onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();doSearch()}};
sr.onclick=e=>{const item=e.target.closest(".book-search-item");if(!item)return;const r=lastSR[parseInt(item.dataset.idx)];if(!r)return;document.getElementById("fTitle").value=r.title;document.getElementById("fAuthor").value=r.author||"";if(r.pages)document.getElementById("fPages").value=r.pages;const cs=document.getElementById("fCategory");for(let i=0;i<cs.options.length;i++)if(cs.options[i].value===r.category){cs.selectedIndex=i;break}sr.innerHTML="";document.getElementById("fTitle").focus()}}
// Save
document.getElementById("formSave").onclick=()=>{const title=document.getElementById("fTitle").value.trim();if(!title)return;const now=new Date().toISOString();const bd={title,author:document.getElementById("fAuthor").value.trim(),category:document.getElementById("fCategory").value,status:document.getElementById("fStatus").value,pages:parseInt(document.getElementById("fPages").value)||null,currentPage:0,startDate:document.getElementById("fStart").value,endDate:document.getElementById("fEnd").value,notes:document.getElementById("fNotes").value.trim(),updatedAt:now};if(isEdit)Object.assign(book,bd);else{bd.id=uid();bd.addedAt=now;bd.rating=0;bd.themes=[];bd.quotes=[];bd.connections=[];bd.coreArgument="";bd.impact="";bd.sessions=[];bd.recommendedBy="";bd.recommendationNote="";bd.recommendationSource="";bd.priority=0;data.books.push(bd)}save();document.getElementById("formModal").classList.remove("open");renderAll()}}

// ══════ SETTINGS ══════
function openSettings(){const lastExpStr=data.settings.lastExport?fmtDate(data.settings.lastExport):"Never";const challenges=data.settings.goals.challenges||[];
let challengeHTML=challenges.map(ch=>{const prog=getChallengeProgress(ch);return`<div class="challenge-card${prog.done?" challenge-done":""}"><p class="challenge-label">${esc(ch.label)}</p><p class="challenge-meta">${ch.type} \u00B7 ${prog.current}/${ch.target}</p><div class="challenge-progress-bar"><div class="challenge-progress-fill" style="width:${prog.pct}%"></div></div><p class="challenge-pct">${prog.pct}%</p><button class="challenge-del" data-chid="${ch.id}">&times;</button></div>`}).join("");
document.getElementById("settingsPanel").innerHTML=`<div class="modal-header"><h2>Settings</h2><button class="modal-close" id="settingsClose">&times;</button></div><div>
<div class="settings-item"><p class="settings-label">Annual Reading Goal</p><input class="settings-num" type="number" id="sGoal" value="${getGoal()}" min="1" max="500"></div>
<div class="settings-item"><p class="settings-label">Category Goals</p><p class="settings-desc">Set targets per category.</p><div class="goal-cat-grid" id="catGoalGrid">${CATEGORIES.map(c=>`<div class="goal-cat-item"><span style="flex:1">${c}</span><input type="number" min="0" max="100" data-cat="${esc(c)}" class="cat-goal-input" value="${(data.settings.goals.categories||{})[c]||""}" placeholder="\u2014"></div>`).join("")}</div></div>
<div class="settings-item"><p class="settings-label">Challenges</p>${challengeHTML||'<p style="font-family:var(--ui);font-size:12px;color:var(--textD)">No challenges yet.</p>'}<button class="settings-btn" id="sAddChallenge" style="margin-top:8px">+ Add Challenge</button><div id="challengeFormArea"></div></div>
<div class="settings-item"><p class="settings-label">Export</p><p class="settings-desc">${lastExpStr!=="Never"?"Last: "+lastExpStr:""}</p><div style="display:flex;gap:8px"><button class="settings-btn" id="sExport" style="flex:1">JSON</button><button class="settings-btn" id="sExportCSV" style="flex:1">CSV</button></div></div>
<div class="settings-item"><p class="settings-label">Import Library</p><button class="settings-btn" id="sImport">Import JSON</button></div>
<div class="settings-item"><p class="settings-label">Reset Demo</p><button class="settings-btn" id="sReset">Reload Sample Data</button></div>
<div class="settings-item"><p class="settings-label">Clear All</p><button class="settings-btn danger" id="sClear">Clear Everything</button></div></div>`;
document.getElementById("settingsModal").classList.add("open");
document.getElementById("settingsClose").onclick=()=>document.getElementById("settingsModal").classList.remove("open");
document.getElementById("sGoal").onchange=e=>{data.settings.goals.annual=parseInt(e.target.value)||50;data.settings.goal=data.settings.goals.annual;save();renderAll()};
document.querySelectorAll(".cat-goal-input").forEach(inp=>inp.onchange=()=>{const cat=inp.dataset.cat,val=parseInt(inp.value)||0;if(!data.settings.goals.categories)data.settings.goals.categories={};if(val>0)data.settings.goals.categories[cat]=val;else delete data.settings.goals.categories[cat];save()});
// Add Challenge
document.getElementById("sAddChallenge").onclick=()=>{const area=document.getElementById("challengeFormArea");if(area.innerHTML){area.innerHTML="";return}area.innerHTML=`<div style="background:var(--bg);border:1px solid var(--borderL);border-radius:10px;padding:14px;margin-top:8px"><div style="margin-bottom:8px"><p class="form-label">Label</p><input class="form-input" id="chLabel" placeholder="Read 3 books over 400 pages"></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:8px"><div><p class="form-label">Type</p><select class="form-input" id="chType"><option value="count">Book Count</option><option value="pages">Total Pages</option><option value="category">Category Count</option><option value="diversity">Category Diversity</option></select></div><div><p class="form-label">Target</p><input class="form-input" type="number" id="chTarget" placeholder="10" min="1"></div></div><button class="rbtn save" id="chSave">Create</button></div>`;document.getElementById("chSave").onclick=()=>{const label=document.getElementById("chLabel").value.trim();if(!label)return;data.settings.goals.challenges.push({id:uid(),label,type:document.getElementById("chType").value,target:parseInt(document.getElementById("chTarget").value)||1,categoryFilter:null,minPages:null,deadline:null});save();openSettings()}};
document.querySelectorAll(".challenge-del").forEach(b=>b.onclick=()=>{data.settings.goals.challenges=data.settings.goals.challenges.filter(c=>c.id!==b.dataset.chid);save();openSettings()});
document.getElementById("sExport").onclick=()=>{const j=JSON.stringify(data,null,2),b=new Blob([j],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`reading-ledger-${new Date().toISOString().slice(0,10)}.json`;a.click();data.settings.lastExport=new Date().toISOString();save();openSettings()};
document.getElementById("sExportCSV").onclick=()=>{exportCSV();openSettings()};
document.getElementById("sImport").onclick=()=>{document.getElementById("importFile").click()};
document.getElementById("sReset").onclick=()=>{data=makeDemoData();save();document.getElementById("settingsModal").classList.remove("open");pickRandomQuote();renderAll()};
document.getElementById("sClear").onclick=()=>{showConfirm("Clear All","Delete everything?",()=>{data={books:[],settings:{goal:50,lastExport:null,goals:{annual:50,categories:{},challenges:[]}}};save();document.getElementById("settingsModal").classList.remove("open");renderAll()})};
}

// ══════ CONFIRM / IMPORT ══════
function showConfirm(t,m,cb){document.getElementById("confirmTitle").textContent=t;document.getElementById("confirmMsg").textContent=m;confirmCb=cb;document.getElementById("confirmOverlay").classList.add("open")}
document.getElementById("confirmOk").onclick=()=>{document.getElementById("confirmOverlay").classList.remove("open");if(confirmCb){confirmCb();confirmCb=null}};
document.getElementById("confirmCancel").onclick=()=>{document.getElementById("confirmOverlay").classList.remove("open");confirmCb=null};
// Import
document.getElementById("importFile").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{pendingImport=JSON.parse(r.result);if(!pendingImport.books)throw 0;document.getElementById("importOverlay").classList.add("open")}catch(e){alert("Invalid backup file.")}};r.readAsText(f);e.target.value=""});
document.getElementById("importReplace").onclick=()=>{document.getElementById("importOverlay").classList.remove("open");if(pendingImport){data=pendingImport;if(!data.settings.goals)data.settings.goals={annual:50,categories:{},challenges:[]};data.books.forEach(b=>{if(!b.sessions)b.sessions=[];if(!b.themes)b.themes=[];if(!b.quotes)b.quotes=[];if(!b.connections)b.connections=[]});save();pendingImport=null;renderAll()}};
document.getElementById("importMerge").onclick=()=>{document.getElementById("importOverlay").classList.remove("open");if(pendingImport){const ex=new Set(data.books.map(b=>`${(b.title||"").toLowerCase()}|${(b.author||"").toLowerCase()}`));pendingImport.books.forEach(b=>{const k=`${(b.title||"").toLowerCase()}|${(b.author||"").toLowerCase()}`;if(!ex.has(k)){if(!b.sessions)b.sessions=[];if(!b.themes)b.themes=[];if(!b.quotes)b.quotes=[];if(!b.connections)b.connections=[];data.books.push(b);ex.add(k)}});save();pendingImport=null;renderAll()}};
function onImportData(json){try{pendingImport=JSON.parse(json);if(!pendingImport.books)throw 0;document.getElementById("importOverlay").classList.add("open")}catch(e){alert("Invalid backup file.")}}

// ══════ WIRING ══════
function switchTab(t){if(t===currentTab)return;const map={shelf:"viewShelf",timeline:"viewTimeline",analytics:"viewAnalytics",review:"viewReview"};document.getElementById(map[currentTab]).classList.remove("active");currentTab=t;document.querySelectorAll("#bottomNav button,#navTabs button").forEach(b=>b.classList.toggle("active",b.dataset.tab===t));document.getElementById(map[t]).classList.add("active");renderAll()}
document.querySelectorAll("#bottomNav button,#navTabs button").forEach(tab=>tab.onclick=()=>switchTab(tab.dataset.tab));
document.getElementById("btnSearch").onclick=()=>{searchOpen=!searchOpen;document.getElementById("searchBar").style.display=searchOpen?"block":"none";document.getElementById("btnSearch").classList.toggle("active",searchOpen);if(searchOpen)document.getElementById("searchInput").focus();else{searchQuery="";renderShelf()}};
let _st;document.getElementById("searchInput").oninput=e=>{clearTimeout(_st);const v=e.target.value;_st=setTimeout(()=>{searchQuery=v;renderShelf()},250)};
document.getElementById("fab").onclick=()=>openForm(null);document.getElementById("btnSettings").onclick=openSettings;
["formModal","settingsModal"].forEach(id=>document.getElementById(id).onclick=function(e){if(e.target===this)this.classList.remove("open")});
function renderAll(){updateHeader();renderShelf();if(currentTab==="timeline")renderTimeline();if(currentTab==="analytics")renderAnalytics();if(currentTab==="review")renderReview()}
renderAll();
checkOnboarding();
