/* ═══ INSIGHT ENGINE — 50 pattern detectors for Year in Review ═══ */
function buildInsightEngine(){
const pick=(...o)=>o[Math.floor(Math.random()*o.length)];
return[
// PACE & VOLUME (1-10)
(c)=>{const tp=c.reduce((s,b)=>s+(b.pages||0),0);if(tp>=10000)return{id:1,cat:'pace',weight:9,text:`You've turned ${tp.toLocaleString()} pages this year \u2014 roughly ${Math.round(tp/250)} average books' worth.`};if(tp>=5000)return{id:1,cat:'pace',weight:7,text:`${tp.toLocaleString()} pages read. ${pick("That's a serious volume.","You're building something.")}`};if(tp>=2000)return{id:1,cat:'pace',weight:4,text:`${tp.toLocaleString()} pages and counting.`};return null},
(c)=>{const l=c.reduce((a,b)=>(b.pages||0)>(a.pages||0)?b:a,c[0]);if(l.pages>=800)return{id:2,cat:'pace',weight:7,text:`${l.title} at ${l.pages.toLocaleString()} pages was a ${pick("marathon","beast","commitment")} \u2014 and you finished it.`};if(l.pages>=500)return{id:2,cat:'pace',weight:5,text:`Your longest read was ${l.title} at ${l.pages} pages.`};return null},
(c)=>{const p=c.filter(b=>b.pages).map(b=>b.pages);if(p.length<3)return null;const r=Math.max(...p)/Math.min(...p);if(r>=4)return{id:3,cat:'pace',weight:6,text:`Your books ranged from ${Math.min(...p)} to ${Math.max(...p).toLocaleString()} pages \u2014 a ${Math.round(r)}x spread.`};return null},
(c)=>{if(c.length<4)return null;const s=[...c].sort((a,b)=>new Date(a.endDate)-new Date(b.endDate));const h=Math.floor(s.length/2);const a1=s.slice(0,h).reduce((x,b)=>x+(b._days||30),0)/h;const a2=s.slice(h).reduce((x,b)=>x+(b._days||30),0)/(s.length-h);if(a1-a2>7)return{id:4,cat:'pace',weight:6,text:`You're reading faster as the year goes on \u2014 recent books took ${Math.round(a2)} days on average, down from ${Math.round(a1)}.`};if(a2-a1>7)return{id:4,cat:'pace',weight:5,text:`Your pace has slowed \u2014 earlier books averaged ${Math.round(a1)} days, recent ones ${Math.round(a2)}.`};return null},
(c)=>{const w=c.filter(b=>b._days>0);if(!w.length)return null;const f=w.reduce((a,b)=>a._days<b._days?a:b);if(f._days<=3)return{id:5,cat:'pace',weight:8,text:`You devoured ${f.title} in just ${f._days} day${f._days!==1?'s':''}. ${pick("Couldn't put it down.","That's a page-turner.")}`};if(f._days<=10)return{id:5,cat:'pace',weight:6,text:`Your fastest finish was ${f.title} \u2014 ${f._days} days.`};return null},
(c)=>{const w=c.filter(b=>b._days>0);if(w.length<3)return null;const s=w.reduce((a,b)=>a._days>b._days?a:b);if(s._days>=60)return{id:6,cat:'pace',weight:5,text:`${s.title} took ${s._days} days \u2014 ${pick("a slow burn","you took your time with that one")}.`};return null},
(c)=>{if(c.length<3)return null;const d=c.map(b=>new Date(b.endDate));const mo=Math.max(1,(Math.max(...d)-Math.min(...d))/(30.44*86400000));const r=c.length/mo;if(r>=3)return{id:7,cat:'pace',weight:7,text:`You're averaging ${r.toFixed(1)} books per month \u2014 a serious clip.`};if(r>=1.5)return{id:7,cat:'pace',weight:4,text:`About ${r.toFixed(1)} books per month \u2014 a steady rhythm.`};return null},
(c)=>{const mc={};c.forEach(b=>{if(b.endDate){const k=b.endDate.slice(0,7);mc[k]=(mc[k]||0)+1}});const best=Object.entries(mc).sort((a,b)=>b[1]-a[1])[0];if(!best||best[1]<2)return null;const[y,m]=best[0].split('-');const mn=new Date(+y,+m-1).toLocaleDateString('en-US',{month:'long'});if(best[1]>=4)return{id:8,cat:'pace',weight:8,text:`${mn} was your powerhouse \u2014 ${best[1]} books in a single month.`};return{id:8,cat:'pace',weight:5,text:`${mn} was your best month with ${best[1]} finishes.`}},
(c)=>{if(c.length<3)return null;const d=c.map(b=>new Date(b.endDate)).sort((a,b)=>a-b);let mg=0,ga=null;for(let i=1;i<d.length;i++){const g=(d[i]-d[i-1])/86400000;if(g>mg){mg=g;ga=d[i-1]}}if(mg>=45){const mn=ga.toLocaleDateString('en-US',{month:'long'});return{id:9,cat:'pace',weight:6,text:`You had a ${Math.round(mg)}-day gap after ${mn} \u2014 ${pick("a reading drought","life got busy")}.`}}return null},
(c)=>{const mc={};c.forEach(b=>{if(b.endDate)mc[b.endDate.slice(0,7)]=true});const mo=Object.keys(mc).sort();if(mo.length<3)return null;let st=1,mx=1;for(let i=1;i<mo.length;i++){const[py,pm]=mo[i-1].split('-').map(Number);const ex=pm===12?`${py+1}-01`:`${py}-${String(pm+1).padStart(2,'0')}`;if(mo[i]===ex){st++;if(st>mx)mx=st}else st=1}if(mx>=4)return{id:10,cat:'pace',weight:7,text:`You finished at least one book every month for ${mx} months straight. ${pick("That's consistency.","Steady hands.")}`};return null},
// CATEGORIES (11-20)
(c)=>{if(c.length<4)return null;const cc={};c.forEach(b=>cc[b.category]=(cc[b.category]||0)+1);const t=Object.entries(cc).sort((a,b)=>b[1]-a[1])[0];const p=Math.round(t[1]/c.length*100);if(p>=50)return{id:11,cat:'category',weight:6,text:`${t[0]} dominates at ${p}% of your reading. ${pick("You know what you like.","Deep in that lane.")}`};if(p>=40)return{id:11,cat:'category',weight:4,text:`${t[0]} is your gravitational center \u2014 ${t[1]} of ${c.length} books.`};return null},
(c)=>{if(c.length<5)return null;const cc={};c.forEach(b=>cc[b.category]=(cc[b.category]||0)+1);const sg=Object.entries(cc).filter(([,v])=>v===1);if(sg.length===1){const bk=c.find(b=>b.category===sg[0][0]);return{id:12,cat:'category',weight:5,text:`${bk.title} was your only ${bk.category} book \u2014 ${pick("a one-off exploration","a detour from your usual path")}.`}}return null},
(c)=>{if(c.length<4)return null;const s=[...c].sort((a,b)=>new Date(a.endDate)-new Date(b.endDate));const h=Math.floor(s.length/2);const t1={},t2={};s.slice(0,h).forEach(b=>t1[b.category]=(t1[b.category]||0)+1);s.slice(h).forEach(b=>t2[b.category]=(t2[b.category]||0)+1);const c1=Object.entries(t1).sort((a,b)=>b[1]-a[1])[0][0];const c2=Object.entries(t2).sort((a,b)=>b[1]-a[1])[0][0];if(c1!==c2)return{id:13,cat:'category',weight:7,text:`Your reading shifted from ${c1} early on to ${c2} more recently \u2014 ${pick("your interests are evolving","a clear pivot","you followed your curiosity")}.`};return null},
(c)=>{const cats=new Set(c.map(b=>b.category)).size;if(c.length>=6&&cats/c.length>=0.7)return{id:14,cat:'category',weight:6,text:`${cats} categories across ${c.length} books \u2014 you rarely read the same genre twice in a row.`};return null},
(c)=>{const cats=new Set(c.map(b=>b.category)).size;if(c.length>=6&&cats<=2)return{id:15,cat:'category',weight:5,text:`You've stayed in just ${cats} categor${cats===1?'y':'ies'} \u2014 ${pick("deep over wide","focused and intentional")}.`};return null},
(c)=>{if(c.length<3)return null;const s=[...c].sort((a,b)=>new Date(a.endDate)-new Date(b.endDate));const seen=new Set();let nw=null;s.forEach(b=>{if(!seen.has(b.category))nw=b;seen.add(b.category)});if(nw&&seen.size>=3)return{id:16,cat:'category',weight:4,text:`${nw.title} was your first ${nw.category} book.`};return null},
(c)=>{const s=[...c].sort((a,b)=>new Date(a.endDate)-new Date(b.endDate));let run=1,mx=1,rc=s[0]?.category;for(let i=1;i<s.length;i++){if(s[i].category===s[i-1].category){run++;if(run>mx){mx=run;rc=s[i].category}}else run=1}if(mx>=3)return{id:17,cat:'category',weight:7,text:`You read ${mx} ${rc} books in a row \u2014 ${pick("a deep dive","fully locked in")}.`};return null},
(c)=>{if(c.length<4)return null;const f=c.filter(b=>b.category==='Fiction').length;if(f===0)return{id:18,cat:'category',weight:4,text:`All nonfiction this year. ${pick("You read to learn, not to escape.","Facts over fiction.")}`};if(Math.round(f/c.length*100)>=70)return{id:18,cat:'category',weight:4,text:`${Math.round(f/c.length*100)}% fiction \u2014 you're a storyteller at heart.`};return null},
(c,all)=>{const ab=all.filter(b=>b.status==='abandoned');if(!ab.length)return null;const abC=new Set(ab.map(b=>b.category));const coC=new Set(c.map(b=>b.category));const only=[...abC].filter(x=>!coC.has(x));if(only.length){const bk=ab.find(b=>b.category===only[0]);return{id:19,cat:'category',weight:5,text:`You tried ${bk.category} with ${bk.title} but didn't finish \u2014 ${pick("not every experiment works","you know when to cut your losses")}.`}}return null},
(c)=>{if(c.length<6)return null;const s=[...c].sort((a,b)=>new Date(a.endDate)-new Date(b.endDate));const h=Math.floor(s.length/2);const c1=new Set(s.slice(0,h).map(b=>b.category)).size;const c2=new Set(s.slice(h).map(b=>b.category)).size;if(c2>c1+1)return{id:20,cat:'category',weight:5,text:`You're broadening \u2014 recent reads span ${c2} categories versus ${c1} earlier.`};return null},
// RATINGS (21-30)
(c)=>{const r=c.filter(b=>b.rating);if(r.length<4)return null;const a=r.reduce((s,b)=>s+b.rating,0)/r.length;if(a>=4.5)return{id:21,cat:'rating',weight:5,text:`You averaged ${a.toFixed(1)}/5 \u2014 ${pick("you pick books well","high standards, well met")}.`};return null},
(c)=>{const r=c.filter(b=>b.rating);if(r.length<4)return null;const a=r.reduce((s,b)=>s+b.rating,0)/r.length;if(a<=3.2)return{id:22,cat:'rating',weight:5,text:`Average rating ${a.toFixed(1)}/5 \u2014 ${pick("you don't give stars away easily","tough but fair")}.`};return null},
(c)=>{const r=[...c].filter(b=>b.rating&&b.endDate).sort((a,b)=>new Date(a.endDate)-new Date(b.endDate));if(r.length<5)return null;const h=Math.floor(r.length/2);const a1=r.slice(0,h).reduce((s,b)=>s+b.rating,0)/h;const a2=r.slice(h).reduce((s,b)=>s+b.rating,0)/(r.length-h);if(a2-a1>=0.8)return{id:23,cat:'rating',weight:6,text:`Your ratings are climbing \u2014 picking better books or growing more generous.`};if(a1-a2>=0.8)return{id:23,cat:'rating',weight:6,text:`Your ratings have dipped over time \u2014 your standards are rising.`};return null},
(c)=>{const s=[...c].filter(b=>b.rating===5&&b.endDate).sort((a,b)=>new Date(a.endDate)-new Date(b.endDate));if(!s.length||c.indexOf(s[0])===0)return null;return{id:24,cat:'rating',weight:4,text:`${s[0].title} earned your first 5 stars.`}},
(c)=>{const r=c.filter(b=>b.rating);if(r.length<5)return null;const cr={};r.forEach(b=>{if(!cr[b.category])cr[b.category]=[];cr[b.category].push(b.rating)});const ca=Object.entries(cr).filter(([,v])=>v.length>=2).map(([k,v])=>[k,v.reduce((a,b)=>a+b,0)/v.length]);if(!ca.length)return null;const best=ca.sort((a,b)=>b[1]-a[1])[0];return{id:25,cat:'rating',weight:5,text:`${best[0]} books scored highest at ${best[1].toFixed(1)}/5 average.`}},
(c)=>{const f=c.filter(b=>b.rating===5);if(f.length<2)return null;const cats=new Set(f.map(b=>b.category));if(cats.size===1)return{id:26,cat:'rating',weight:6,text:`All your 5-star books are ${[...cats][0]} \u2014 that's where your heart is.`};return null},
(c)=>{const r=c.filter(b=>b.rating);if(r.length<4)return null;const mn=Math.min(...r.map(b=>b.rating));if(mn>=4)return{id:27,cat:'rating',weight:5,text:`Never below ${mn} stars \u2014 ${pick("you curate well","no regret reads")}.`};return null},
(c)=>{const r=c.filter(b=>b.rating&&b.pages);if(r.length<5)return null;const lo=r.filter(b=>b.pages>=400),sh=r.filter(b=>b.pages<400);if(lo.length<2||sh.length<2)return null;const al=lo.reduce((s,b)=>s+b.rating,0)/lo.length,as=sh.reduce((s,b)=>s+b.rating,0)/sh.length;if(al-as>=0.5)return{id:28,cat:'rating',weight:5,text:`You rate longer books higher (${al.toFixed(1)} vs ${as.toFixed(1)}) \u2014 length earns your respect.`};if(as-al>=0.5)return{id:28,cat:'rating',weight:5,text:`Shorter books score better with you (${as.toFixed(1)} vs ${al.toFixed(1)}) \u2014 concise wins.`};return null},
(c)=>{const s=[...c].filter(b=>b.endDate).sort((a,b)=>new Date(a.endDate)-new Date(b.endDate));for(let i=1;i<s.length;i++){if(s[i].rating===5&&s[i-1].rating===5)return{id:29,cat:'rating',weight:7,text:`${s[i-1].title} and ${s[i].title} \u2014 back-to-back 5 stars. ${pick("A golden streak.","You were on a roll.")}`}}return null},
(c)=>{const r=c.filter(b=>b.rating);if(r.length<5)return null;if(new Set(r.map(b=>b.rating)).size===1)return{id:30,cat:'rating',weight:5,text:`Every book got ${r[0].rating} stars \u2014 ${pick("consistent taste","remarkably uniform")}.`};return null},
// THEMES (31-38)
(c)=>{const th={};c.forEach(b=>(b.themes||[]).forEach(t=>th[t]=(th[t]||0)+1));const top=Object.entries(th).sort((a,b)=>b[1]-a[1])[0];if(!top||top[1]<3)return null;return{id:31,cat:'theme',weight:5,text:`"${top[0]}" runs through ${top[1]} of your books \u2014 a thread you keep pulling.`}},
(c)=>{const th={};c.forEach(b=>(b.themes||[]).forEach(t=>{if(!th[t])th[t]=[];th[t].push(b.title)}));const cl=Object.entries(th).filter(([,v])=>v.length>=3);if(!cl.length)return null;const[theme,books]=cl.sort((a,b)=>b[1].length-a[1].length)[0];return{id:32,cat:'theme',weight:6,text:`${books.length} books touch on "${theme}" \u2014 ${pick("a pattern emerging","you're circling something")}.`}},
(c)=>{const th={};c.forEach(b=>(b.themes||[]).forEach(t=>th[t]=(th[t]||0)+1));const sg=Object.entries(th).filter(([,v])=>v===1);if(sg.length>3&&Object.keys(th).length>5)return{id:33,cat:'theme',weight:3,text:`${sg.length} themes appeared in only one book \u2014 lots of one-off explorations.`};return null},
(c)=>{if(c.length<6)return null;const s=[...c].sort((a,b)=>new Date(a.endDate)-new Date(b.endDate));const h=Math.floor(s.length/2);const t1={},t2={};s.slice(0,h).forEach(b=>(b.themes||[]).forEach(t=>t1[t]=(t1[t]||0)+1));s.slice(h).forEach(b=>(b.themes||[]).forEach(t=>t2[t]=(t2[t]||0)+1));const top1=Object.entries(t1).sort((a,b)=>b[1]-a[1])[0];const top2=Object.entries(t2).sort((a,b)=>b[1]-a[1])[0];if(top1&&top2&&top1[0]!==top2[0])return{id:34,cat:'theme',weight:6,text:`Early on you were drawn to "${top1[0]}" \u2014 lately it's "${top2[0]}."`};return null},
(c)=>{const low=c.filter(b=>b.rating&&b.rating<=2&&(b.themes||[]).length);if(low.length<2)return null;const th={};low.forEach(b=>(b.themes||[]).forEach(t=>th[t]=(th[t]||0)+1));const top=Object.entries(th).sort((a,b)=>b[1]-a[1])[0];if(top&&top[1]>=2)return{id:35,cat:'theme',weight:5,text:`"${top[0]}" appears in your lowest-rated books \u2014 the topic interests you, the execution doesn't.`};return null},
(c)=>{const mx=c.reduce((best,b)=>(b.quotes||[]).length>(best.quotes||[]).length?b:best,c[0]);const q=(mx.quotes||[]).length;if(q>=5)return{id:36,cat:'theme',weight:6,text:`You saved ${q} passages from ${mx.title} \u2014 ${pick("it clearly hit differently","heavily bookmarked")}.`};return null},
(c)=>{const an=c.filter(b=>b.notes||b.coreArgument||b.impact||(b.quotes||[]).length);const p=Math.round(an.length/c.length*100);if(p>=80&&c.length>=4)return{id:37,cat:'theme',weight:5,text:`${p}% of your books have notes or quotes \u2014 ${pick("you read with a pen in hand","deeply engaged")}.`};if(p<=20&&c.length>=5)return{id:37,cat:'theme',weight:3,text:`Only ${an.length} of ${c.length} books have notes \u2014 you read clean.`};return null},
(c)=>{const w=c.filter(b=>b.coreArgument||b.impact);if(w.length>=3&&w.length<c.length)return{id:38,cat:'theme',weight:3,text:`${w.length} books have takeaways recorded \u2014 the rest are still percolating.`};return null},
// TEMPORAL (39-46)
(c,all)=>{const ss=[];all.forEach(b=>(b.sessions||[]).forEach(s=>{if(s.date)ss.push(s)}));if(ss.length<10)return null;let we=0,wd=0;ss.forEach(s=>{const d=new Date(s.date).getDay();if(d===0||d===6)we++;else wd++});const p=Math.round(we/ss.length*100);if(p>=55)return{id:39,cat:'temporal',weight:5,text:`${p}% of your sessions are on weekends \u2014 ${pick("you read when you rest","a weekend ritual")}.`};if(p<=25)return{id:39,cat:'temporal',weight:5,text:`Most reading happens on weekdays \u2014 ${pick("reading is part of your routine","you make time during the grind")}.`};return null},
(c)=>{if(c.length<6)return null;const q=[0,0,0,0];c.forEach(b=>{if(b.endDate){const m=new Date(b.endDate).getMonth();q[Math.floor(m/3)]++}});const lb=['winter','spring','summer','fall'];const mx=Math.max(...q),mi=q.indexOf(mx);if(mx>=3&&mx>c.length*0.4)return{id:40,cat:'temporal',weight:6,text:`You read the most in ${lb[mi]} \u2014 ${pick("seasonal momentum","that's your season")}.`};return null},
(c)=>{if(c.length<3)return null;const s=[...c].sort((a,b)=>new Date(a.endDate)-new Date(b.endDate));const f=s[0],l=s[s.length-1];return{id:41,cat:'temporal',weight:3,text:`Your year went from ${f.title} to ${l.title} \u2014 ${f.category===l.category?"started and ended in the same lane":"a journey from "+f.category+" to "+l.category}.`}},
(c,all)=>{const r=all.filter(b=>b.status==='reading');if(r.length>=3)return{id:42,cat:'temporal',weight:5,text:`You're juggling ${r.length} books at once right now \u2014 ${pick("a parallel reader","multiple threads running")}.`};return null},
(c)=>{if(c.length<3)return null;const s=[...c].filter(b=>b.endDate&&b.startDate).sort((a,b)=>new Date(a.endDate)-new Date(b.endDate));let q=Infinity,pr=null;for(let i=1;i<s.length;i++){const g=(new Date(s[i].startDate)-new Date(s[i-1].endDate))/86400000;if(g>=0&&g<q){q=g;pr=[s[i-1],s[i]]}}if(q<=1&&pr)return{id:43,cat:'temporal',weight:5,text:`You started ${pr[1].title} right after finishing ${pr[0].title} \u2014 ${pick("no downtime","always the next book ready")}.`};return null},
(c,all)=>{let lg=null;all.forEach(b=>(b.sessions||[]).forEach(s=>{if(s.duration&&(!lg||s.duration>lg.dur))lg={dur:s.duration,title:b.title}}));if(lg&&lg.dur>=120)return{id:44,cat:'temporal',weight:5,text:`Your longest session was ${Math.round(lg.dur/60)} hours on ${lg.title} \u2014 ${pick("deep in the zone","a proper marathon session")}.`};return null},
()=>null, // 45: abandoned-then-returned (needs history)
(c)=>{const most=c.reduce((best,b)=>(b.sessions||[]).length>(best.sessions||[]).length?b:best,c[0]);const n=(most.sessions||[]).length;if(n>=8)return{id:46,cat:'temporal',weight:5,text:`${most.title} took ${n} sessions to finish \u2014 ${pick("a long relationship with that book","savored, not rushed")}.`};return null},
// SOCIAL & META (47-50)
(c,all)=>{const rc={};all.forEach(b=>{if(b.recommendedBy)rc[b.recommendedBy]=(rc[b.recommendedBy]||0)+1});const top=Object.entries(rc).sort((a,b)=>b[1]-a[1])[0];if(top&&top[1]>=2)return{id:47,cat:'social',weight:6,text:`${top[0]} has recommended ${top[1]} books to you \u2014 ${pick("your reading advisor","a trusted source")}.`};return null},
(c,all)=>{const rc=all.filter(b=>b.recommendedBy).length;if(rc===0&&all.length>=5)return{id:48,cat:'social',weight:4,text:`Every book was self-discovered \u2014 ${pick("you chart your own path","independent taste")}.`};return null},
(c,all)=>{const bl=all.filter(b=>b.status==='want-to-read').length;if(bl>=10)return{id:49,cat:'social',weight:5,text:`${bl} books in your want-to-read pile \u2014 ${pick("no shortage of what's next","the list grows faster than the shelf")}.`};if(bl>=5&&c.length<bl)return{id:49,cat:'social',weight:4,text:`Your backlog (${bl}) is growing faster than your completed list (${c.length}).`};return null},
(c,all)=>{const ab=all.filter(b=>b.status==='abandoned').length;const total=c.length+ab;if(total<4)return null;if(ab===0)return{id:50,cat:'social',weight:4,text:`You've finished every book you've started \u2014 ${pick("100% completion rate","you see things through")}.`};if(c.length/(total)<=0.7)return{id:50,cat:'social',weight:5,text:`${ab} abandoned out of ${total} started \u2014 you're not afraid to quit a book that isn't working.`};return null}
];}

function generateInsights(allBooks){
  const comp=allBooks.filter(b=>b.status==='completed');
  if(comp.length<3)return[];
  comp.forEach(b=>{if(b.startDate&&b.endDate)b._days=Math.max(1,Math.round((new Date(b.endDate)-new Date(b.startDate))/86400000))});
  const detectors=buildInsightEngine();const results=[];
  detectors.forEach(d=>{try{const r=d(comp,allBooks);if(r)results.push(r)}catch(e){}});
  results.sort((a,b)=>b.weight-a.weight);
  const seen=new Set(),deduped=[];
  results.forEach(r=>{if(!seen.has(r.cat)){deduped.push(r);seen.add(r.cat)}});
  return deduped.slice(0,3);
}

function composeInsightText(allBooks){
  const insights=generateInsights(allBooks);
  return insights.map(i=>i.text).join(' ');
}
